# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  systemd.network = {
    enable = true;

    networks."10-opal" = {
      matchConfig.Name = "ens3";

      address = [
        "89.58.6.171/22"
        "2a03:4000:5e:10::/64"
      ];

      routes = [
        { Gateway = "89.58.4.1"; }
        { Gateway = "fe80::1"; }
      ];

      linkConfig.RequiredForOnline = "routable";
    };
  };
}
